#!/bin/sh
#/
#/ Setup the local environment
#/

cd $(dirname $0)/..
BASEDIR=$(pwd -P)

# we got banners
awk '/^#\//{print substr($0,4)}' $0

# rubby
rm -rf .bundle/config
bundle check --path vendor/gems >/dev/null 2>&1 ||
    bundle install --binstubs bin --path vendor/gems --no-prune

# verify dependencies
/bin/echo -n "Verifying mysql...    "
which mysql 2>/dev/null 1>&2 && echo "OK" || {
  echo "MISSING"
  exit 1
}

/bin/echo -n "Verifying sphinx...   "
which searchd 2>/dev/null 1>&2 && echo "OK" || {
  echo "MISSING"
  exit 1
}


